### PR TITLE
Added the 4 new elements!

### PR DESCRIPTION
**Pull request by randomdude999**
This adds the 4 new elements (nihonium (no. 113), moscovium (no. 115), tennessine (no. 117) and oganesson(no. 118) ) to the `ElementEnum` and (English) lang file. Note that I do not know the names of the elements in other languages, but I hope they are similar enough to English so I don't really need to change them.

My laptop in in no state to compile and test Minecraft mods, so I just have to hope I didn't break anything.

### CODE REVIEW

**Comment by randomdude999** [comment]
Well... that took a while.

**Comment by jakimfett** [comment]
You might want to obtain [context](https://jakimfett.com/status-report/epilogue-modding-minecraft/) before snarking.  
Sometimes, there's a [reason](https://twitter.com/jakimfett/status/976562850805067776) that things happen when they happen.

**Comment by randomdude999** [comment]
Sorry if I sounded snarky, I was just surprised that this got merged at all - in the 1.5 years it's been I've lost interest in Minecraft modding and deleted my fork of this repo too. Anyways, it's nice to know that this is still being worked on.

**Comment by jakimfett** [comment]
My apologies.
I'm...a bit oversensitive about this particular subject at times.
I'll fix my response, there's better ways for me to have handled that.

If...you're willing to discuss:  
I'm curious about your own loss of interest.
Context for me is, of course, as above.

--

Feel like giving a random stranger the `tl:dr` of your thoughts on gaming, player interactions, modding, programming, life, the universe, and everything?

*awkwardly passes you an obviously fake microphone*

**Pull request merged**
